source = $HOME/.config/assets/themes/howls.conf

$accent = $secondary0
$accentAlpha = $accent0Alpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/.config/assets/images/wallpapers/howls-moving-castle.jpg
    #path = ~/.config/assets/images/wallpapers/megumin.png
    blur_passes = 0
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%R")"
    color = $text
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $text
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

shape {
    monitor = -1
    size = 500, 400
    color = $overlay0
    rounding = 30

    position = 25%, 20 
    halign = center
    valign = center
}

# USER AVATAR
image {
    monitor = 
    #path = ~/.config/assets/images/Avatar.jpg
    size = 150
    border_color = $accent

    position = 25%, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    shadow_passes = 3

    monitor =
    size = 350, 90
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = $overlay0
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 25%, -35
    halign = center
    valign = center
}
