# Preload the image into memory
preload = /home/bandit/.config/assets/images/wallpapers/center/all-subaru.jpg
preload = /home/bandit/.config/assets/images/wallpapers/side/frieren-old.jpeg
preload = /home/bandit/.config/assets/images/wallpapers/side/shadow2.jpeg

# Laptop
#preload = /home/bandit/.config/assets/images/wallpapers/frieren-alone.jpeg
#preload = /home/bandit/.config/assets/images/wallpapers/frieren-old.jpeg



# Apply the wallpaper to specific monitors
#HDMI-A-1 is the left portrait monitor
#DP-3 is the Center Ultrawide Monitor
#DP-1 is the right portrait monitor
wallpaper = HDMI-A-1, /home/bandit/.config/assets/images/wallpapers/side/frieren-old.jpeg
wallpaper = DP-3, /home/bandit/.config/assets/images/wallpapers/center/all-subaru.jpg
wallpaper = DP-1, /home/bandit/.config/assets/images/wallpapers/side/shadow2.jpeg

# Laptop
#wallpaper = eDP-1, /home/bandit/.config/assets/images/wallpapers/frieren-alone.jpeg
#wallpaper = HDMI-A-1, /home/bandit/.config/assets/images/wallpapers/frieren-old.jpeg



# Unload the image from memory after use
unload = /home/bandit/.config/assets/images/wallpapers/center/all-subaru.jpg
unload = /home/bandit/.config/assets/images/wallpapers/side/shadow2.jpeg
unload = /home/bandit/.config/assets/images/wallpapers/side/frieren-old.jpeg

# Laptop
#unload = /home/bandit/.config/assets/images/wallpapers/frieren-alone.jpg
#unload = /home/bandit/.config/assets/images/wallpapers/frieren-old.jpeg


# Optional: Disable splash screen
splash = false

# Optional: Enable IPC for dynamic control
ipc = true

